name: Keep Alive

on:
  schedule:
    - cron: '0 12 * * 1'
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Keep alive
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git commit --allow-empty -m "Keep alive"
          git push
